---
title: "scfmCrop"
author: "Module Author"
date: "10 July 2015"
output: pdf_document
---

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

## Input data

## Output data

## Anticipated linkages to other modules


```{r loadShp, echo=FALSE}
library(rgdal)
library(SpaDES)
library(magrittr)
dev.off()
dev(4)
newPlot()
dataDir<-file.path("data", "Ecoregions")
shape <- readOGR(dsn = dataDir, layer = "ecoregions")
Plot(shape)
studyArea<-shape[shape$ECOREGION==87,] #we have chosen Athabasca Plains in northern SK
                                       #we happen to know the numeric code is 87 (easier to type)
print(paste("class(studyArea) =",class(studyArea)))
Plot(studyArea)
```

Now we can test the fire regime estimatorm and its GIS operations, and thr Caching of the database.

```{r module_usage, message=FALSE}
#Make sure to setwd to project directory
try(rm(mySim))
inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(tempdir(), "outputs")
times <- list(start = 0, end = 10)
parameters <- list(
 scfmCrop <- list(
   .useCache = TRUE
 )
)

modules <- list("scfmCrop")
objects <- list(studyArea=studyArea)

paths <- list(
  cachePath = file.path(outputDir, "cache"),
  modulePath = file.path("scfmModules"),
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)
tmp <- spades(mySim,debug=FALSE)
```

