---
title: "ageModule"
author: "Steve Cumming"
date: "24 January 2016"
output: pdf_document
---
#Overview

This module tracks patch "age", usually understood as time since last patch initiating disturbance, but could also be the time since any stochastic event, or the time since birth of a sessile individual.

A ageMap may be provided from the sim environment, or loaded by the .inputObjects event (not implemented here.)

If no map is provided as input, one is initalised using input object __flammableMap__ as template. In that case, all cells are initialised to the value of module parameter __initialAge__.

At every invocation of the event, the elements of ageMap are incremented by one time unit, as specified by the paramater __returnInterval__

If the paramater __maxAge__ is specified, ages are truncated this value. The default is __NA__, in which case the effective maximum age is 2^31-1$ units.

# Usage

On its own, this module is _not_ very interesting. 

```{r module_usage}
library(SpaDES)
library(magrittr)

inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(tempdir(), "outputs")

times <- list(start = 0, end = 10)
parameters <- list(
   ageModule = list(
    initialAge=100, 
    maxAge=250, 
    .plotInitialTime=0
  )
)

modules <- list("ageModule")

objects <- list(flammableMap = raster(raster::extent(0,49,0,49),nrow=50, ncol=50, vals=0))

paths <- list(
    cachePath = file.path(outputDir, "cache"),
    modulePath = file.path("scfmModules"),
    inputPath = inputDir,
    outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

mySim<-spades(mySim)
```

# Events

## Init

The __ageMap__ is created from template __flammableMap__ and initialed to module paramater __initialAge__.

Unless __ageMap__ allready exists in the sim environment; then we don't do that.

In either case, we set the colour scheme.

## Plotting

__ageMap__ is plotted if __.plotInitialTime__ is set to something not __NA__

##Age

Increment all the nonNA elements of __ageMap__ by paramater __returnInterval__.
Enforce paramater __magAge__ or some Large integer if the paramater is __NA__.


# Data dependencies

## Input data

Either _ageMap__ or the template map __flammableMap__ must be provided in the environment.

## Output data

The updated __ageMap__

Any statistics generated by a __Stats__ event would also be output.

# Links to other modules

No explicit links to any other module are envisioned. 

Interactions with other porcesses would be handled by interface modules like module __mapBurns__. 

