---
title: "scfmEscape"
author: "Steve Cumming"
date: "28 February 2018"
output: pdf_document
---

# Overview

Model the escape of fires from their cells of origin, all on the template RasterLayer __flammableMap__.

Spread probabilities are taken from an element of object __scfmPars__ if this exists in the environment, otherwise from
module paramater __pEscape__. The latter option is to facilitate stand alone use, or use outside of the module family __scfm__

This is part of triplet of modules __scfmIgnition__, __scfmEscape__ and __scfmSpread__ which implement the three stage stochastic landscape fire model described in Armstrong and Cumming (2003), and in Cumming, Demarchi and Walters (1998).

# Usage

```{r module_usage}
library(SpaDES)
library(magrittr)
library(raster)
inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(tempdir(), "outputs")
times <- list(start = 0, end = 10)
parameters <- list(
 scfmEscape = list(p0=0.25,           #make sure there's some escape to show.
                   .plotInitialTime=0 #test the Plot event
                   ) 
)
modules <- list("scfmEscape")
objects <- list(flammableMap = raster(raster::extent(0,49,0,49),nrow=50, ncol=50, vals=0),
                ignitionLoci = c(510, 1025, 1530, 2040)
                )
paths <- list(
  cachePath = file.path(outputDir, "cache"),
  modulePath = file.path("."),  #assume run in RStudio for Module directory
  inputPath = inputDir,
  outputPath = outputDir
)
mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

mySim <- spades(mySim)
```

# Events

## Init 

Verify that __nNbrs__ exists in the environment, or else create it as __nNbrs <-  8__.
Set data.table __spreadState <- NULL__. 
No need to verify __flammableMap__ it would be verified by __scfmIgnition.R__.

## ePlot

This maintains RasterLayer escapeMap: it marks the ignitionLoci and initial spread locations, and Plots it.
By default, it does not happen. It can tiggered by setting parameter __.plotInitialTime >= 0__, which triggers escapeMap initialistion in the __Init__ event. 

## Escape



# Data dependencies

## Input data

__flammableMap__ a RasterLayer serving as template. Also, may code non-flammable locations $!=0$ 

__scfmPars__ if present, provides a constant or RasterLayer of ignition probabilities. 

__ignitionLoci__ vector of locations of ignitions. Would normally be generated by module __scfmIgnitions__

The constant __nNbrs__ can be specified in the environment; if absent, the __.inputObjects__ event creates it with default value 8.

## Output data

data.table __spreadStateE__ of initial spread event locations within __flammableMap__, and their states. 


# Links to other modules

This is part of the __scfm__ family of landscape fire models paramaterised from fire agency records.  linkages to other modules.

It is preceded by __scfmIgnitions__ and provides state of spreading fires to __scfmSpread__.

__scfmDriver__ would normally be used to generate paramaters for these processes. 



