---
title: "loadYieldTables"
author: "Module Author"
date: "24 March 2016"
output: pdf_document
---

# Overview

This is a data assimilation module designed to build a library of standardised volume-age tables from disparate raw data sources, for example Provincially sanctioned yield tables.


# Usage

Simply include the module in a sim object.

# Events

There is only the init event. This could be shifted to the .inputObjects even.

## Plotting

Nothing is plotted. The .Rmd file may chose to plot some demonstration yield curves.

# Data dependencies

## Input data

Scans all files ia specified data directory. This would normally be $\tt dataPath(sim)$, but this may be overwritten by parameter $\tt yieldTableDir$. Any subdirectories are taken to contain raw data of some sort, of a format uniquely determined by the subdirectory name. These names would typically refer to the data source, say by code for the Province (e.g. AB) or some spatially defined data provider.  

A switch statement is used to dispatch a hand-tooled handler function which can process the contents of a specific directory. Contents with no handler are ignored with a polite message.

In future versions, we may allow subdirectories to reflect local spatial divisions, e.g. ecoregions in Saskatchewan.

## Output data

The results are a list $\tt yieldTables$ of yield table structures (YTS) indexed by the subdirectory names from which they were loaded.

Each YTS is itself a list of one more yield tables, indexed by an integer or name. The name would normally refer to some local stand-type classification (analysis unit, cover group, etc.) used for forest manangement planning, based e.g.on tree species, stocking density, site quality, ecological region: e.f. "Aw" in Alberta.

Each table consists on an $n\times 3$ matrix. $n$ indexes age annually from 1 to the value of module paramater $\tt yieldTableMaxAge$ which defaults to 240 yrs. Year 1 would refer to the typical harvesting period after the stand originating disturbance, so usually one growing season after the event. 

The first two collumns refer to the deciduous and coniferous volume components, the 3rd collumn is the Total, or the sum of the 1st two. The 3rd collumn is guaranteed to be non zero. The interpretation of the species content of the two volume components is table- and region-specific. At some point, the general methodology developed for Tardis by Cumming and Kenmei will be reimplemented in this module, such that each colummn will refer to a species list.

For the current version, 2018, it would be best to use only the 3rd collumn.

# Links to other modules

The YTS list is meant to drive AAC calculations in module Hanzlik and to drive a harvest scheduler. More generally, this structure would be used by any strategic planning module.


# Module usage

New R users should note the functions read.table() and approx() in function yieldTablesAB.


```{r module_usage}
library(SpaDES)
library(magrittr)

try(rm(mySim))

inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(tempdir(), "outputs")
times <- list(start = 0, end = 10)
parameters <- list(loadYieldTables=list(yieldTableMaxAge=180))
modules <- list("loadYieldTables")
objects <- list()
paths <- list(
  cachePath = file.path(outputDir, "cache"),
  modulePath = file.path("scfmModules"),
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules, paths = paths)

if (exists("mySim")){
  tmp <-spades(mySim)
}
```

#Data Sources

##Alberta (AB)

Verifed by SGC 2018.04.07 from Global Constants in an ancient Visual Basic module Main_S.bas as modifed by sgc 30.08.01

1. Aw     Pure Aspen _Populus tremuloides_
2. Aw/Sw  Aspen with a white spruce _Picea glauca_ understory (never used)
3. AwSw   20-50% Sw (this would be based on AVI or Phase 3 inventory calls)
4. SwAw   50-80% Sw (as above)
5. Sw    "pure" white spruce, >80% Sw.
6. Sb     Black Spruce _Picea mariana_
7. Pj     Jack Pine _Pinus banksiana_ 
8. AwPj   Aspen Pine mixtures (20-50% pine, I think)

You would normally access  a curve as follows

YTS[["AB"]][["Sw"]][,3] would be the matrix collum of total stand volume for table Sw in region AB.
YTS[["AB"]][[5]][,3] would yield the same result in this case.





